[0m20:02:00.969995 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C424CC0FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C4265811B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C426580FD0>]}


============================== 20:02:00.974995 | 96408005-ea85-4306-aadb-b39014290c28 ==============================
[0m20:02:00.974995 [info ] [MainThread]: Running with dbt=1.9.0
[0m20:02:00.975995 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\kali_\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:02:00.976997 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\robert.kali\2mo\mismaostsin_etl_project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:02:00.978996 [debug] [MainThread]: Command `dbt run` failed at 20:02:00.978996 after 0.08 seconds
[0m20:02:00.979997 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C424CC0FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C4265812A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C426581270>]}
[0m20:02:00.979997 [debug] [MainThread]: Flushing usage events
[0m20:02:01.587445 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:59:48.142974 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AF0A2C0F70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AF0B9810F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AF0B980F10>]}


============================== 10:59:48.150165 | 8b3e48d7-4e98-494c-90fe-683664adfb0a ==============================
[0m10:59:48.150165 [info ] [MainThread]: Running with dbt=1.9.0
[0m10:59:48.152817 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\kali_\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m10:59:48.153814 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\robert.kali\2mo\mismaostsin_etl_project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:59:48.155813 [debug] [MainThread]: Command `dbt run` failed at 10:59:48.155813 after 0.12 seconds
[0m10:59:48.156813 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AF0A2C0F70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AF0B9811E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AF0B9811B0>]}
[0m10:59:48.157812 [debug] [MainThread]: Flushing usage events
[0m10:59:48.675122 [debug] [MainThread]: An error was encountered while trying to flush usage events
